### ISSUE TITLE
Prepare initial configurations

### ISSUE THREAD

**Issue by RaudrSkol** [JS-Collaborations-LLC/clip-rating-bot#8]
### 1.7 Prepare initial configurations
- [ ] Create a basic configuration file in the config folder
- [ ] Add placeholder utility functions in the utils folder
- [ ] Set up database connection file in the database folder (if applicable)

**Comment by jSydorowicz21** [comment]
Use a mongo db cluster for databasing, free tier should cover this, you can create an account here:
https://www.mongodb.com
